### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by nmoran** [kahypar/KaHyPar.jl#2]
Got this working on macOS (tests passing) but required a few undocumented steps. Can prepare PR with these if this is something that would be useful. Requires.

1. Building C++ lib and setting JULIA_KAHYPAR_LIBRARY_PATH to point to lib folder
2. Creating a symlink named `libboost_program_options.so` to point to `libboost_program_options.dylib`

To make this easier for others could add details about setting the `JULIA_KAHYPAR_LIBRARY_PATH` to the `README.md` and could update the `build.jl` file to try to load `libboost_program_options.dylib` as well as `libboost_program_options.so`.

**Comment by SebastianSchlag** [comment]
Hi,
thank you for reaching out. I would greatly appreciate a PR and think that @jalving would be OK with this as well. At some point, we were discussing to try to support macOS.

**Comment by nmoran** [comment]
Hi @SebastianSchlag and @jalving, see #3 for attempt at a PR to address this

**Comment by SebastianSchlag** [comment]
I just merged the PR. Thank you very much for your contribution! 👍
