### ISSUE TITLE
in partition occurs signal (11): Segmentation fault: 11

### ISSUE THREAD

**Issue by chenhu822** [kahypar/KaHyPar.jl#21]
Hi, i am now using the partition function to partition a hypergraph and all except the last partition can process well. However, once i run the last partition sequence on VSC, the terminal quits. And then i run julia on my mac terminal, an error in partition occurs signal (11): Segmentation fault: 11 occurs. Could you please help me what is wrong?

#Setup node and edge weights
n_vertices = length(vertices(hypergraph))
node_sizes = [num_variables(node) for node in all_nodes(gas_network)]
edge_weights = [num_linkconstraints(edge) for edge in all_edges(gas_network)]
hyperedges = edges(hypergraph)
hyperedge_indices = vertices(hypergraph)
k = n_processes

hedges = Int32[]
hedge_indices = Int64[0]
for k in keys(hyperedges)
    for e in k
        push!(hedges,e)
    end
    push!(hedge_indices,length(hedges))
end

hypergraph1 = KaHyPar.HyperGraph(n_vertices, hedge_indices, hedges, node_sizes, edge_weights)
node_vector = KaHyPar.partition(hypergraph1,n_parts;imbalance = max_imbalance, configuration = :edge_cut)

**Here is the error:**

822qiuqiu@huchenyudeMacBook-Pro gas_network % julia partition_and\ _solve.jl 
signal (11): Segmentation fault: 11
in expression starting at /Users/822qiuqiu/Desktop/hypergraph/gas_network/partition_and _solve.jl:42
_ZN7kahypar2ds17GenericHypergraphIjjiiiNS_4meta5EmptyES3_EC2EjjPKmPKjiPKiSA_ at /Users/822qiuqiu/.julia/artifacts/839361bcfc9430c57b56f0bad0577fe198831dae/lib/libkahypar.dylib (unknown line)
kahypar_partition at /Users/822qiuqiu/.julia/artifacts/839361bcfc9430c57b56f0bad0577fe198831dae/lib/libkahypar.dylib (unknown line)
kahypar_partition at /Users/822qiuqiu/.julia/packages/KaHyPar/YSKB3/src/kahypar_h.jl:48
unknown function (ip: 0x139db4f70)
#partition#2 at /Users/822qiuqiu/.julia/packages/KaHyPar/YSKB3/src/KaHyPar.jl:111
partition##kw at /Users/822qiuqiu/.julia/packages/KaHyPar/YSKB3/src/KaHyPar.jl:92
unknown function (ip: 0x139db4e7f)
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:117
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:840
jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:913
jl_load_rewrite at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:914 [inlined]
jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:919
include at ./Base.jl:380
include at ./Base.jl:368
exec_options at ./client.jl:296
_start at ./client.jl:506
jfptr__start_57330.clone_1 at /Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
true_main at /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 114763534 (Pool: 114728454; Big: 35080); GC: 85
zsh: segmentation fault  julia partition_and\ _solve.jl

and i check the edge and vertices indices, they are matched and not out of index.

**Comment by SebastianSchlag** [comment]
Hi,
I think we might need more information to debug this properly. Are you sure that

```
node_sizes = [num_variables(node) for node in all_nodes(gas_network)]
edge_weights = [num_linkconstraints(edge) for edge in all_edges(gas_network)]
``

are set correctly? From your code, it looks like the vertices and edges are derived from some `hypergraph`, but node and edge weights are derived from `gas_network`. Does this result in the correct number of node and edge weights?

Could you provide us with a complete example such that we could try to reproduce this locally?

**Comment by jalving** [comment]
As @SebastianSchlag said, it is hard to debug without the full context, but it looks like you are using a hypergraph from Plasmo.jl? In that case, can you try something more like the below snippet? 

```
A = incidence_matrix(hypergraph) # I think this is the same hypergraph you have
node_sizes = Int64.(node_sizes)
edge_weights = Int64.(edge_weights)
kgraph = KaHyPar.HyperGraph(A, node_sizes, edge_weights)
partition_vector = KaHyPar.partition(kgraph, n_parts; imbalance=max_imbalance, configuration=:edge_cut)
```

The issue is likely with using the manual`KaHyPar.HyperGraph` constructor where you are passing in the vertex and edge indices directly as opposed to passing in an incidence matrix. The `KaHyPar.HyperGraph(A::SparseMatrixCSC,vertex_weights::Vector,edge_weights::Vector)` constructor does some type conversions to `Cint` and `Cuint` that the manual constructor does not do (but probably should).

**Comment by chenhu822** [comment]
Thank you for your reply! Now I have edited my code to @jalving snippet and it works!
