### ISSUE TITLE
KaHyPar.jl not supported for Julia on MacBook M1

### ISSUE THREAD

**Issue by JoeyT1994** [kahypar/KaHyPar.jl#22]
I am having issues installing KaHyPar.jl on a MacBook M1 running the lastest ARM build of Julia.

I get the following error:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/51231103/195648940-500462c6-ef24-4298-bc27-617f1ab85e3e.png">

Is this occurring because KaHyPar is not supported on ARM Julia?

**Comment by SebastianSchlag** [comment]
Hi @JoeyT1994, 

we made the changes to support ARM sometime in January (see https://github.com/kahypar/kahypar/pull/100).

@jalving could it be that we need to update something here to bundle the latest KaHyPar version?

**Comment by jalving** [comment]
@SebastianSchlag yes, we need to execute a new build and host the binary. i'm a little rusty on Julia build system since we set that up (with our other contributors). I'll take a look at getting this updated.

**Comment by jalving** [comment]
Quick update; we were able to build and host KaHyPar v.1.3.0 binaries which should support M1, but there are some issues with the Julia interface failing tests. I'll need to dig a bit deeper (and maybe work with Sebastian) to figure out what's going on. 

On a somewhat unrelated note, I made a PR to set the current Julia interface to use KaHyPar v1.2.1 (since it's pulling a failing v1.3.0 right now). We'll work towards a v0.3.0 which should support M1.

**Comment by SebastianSchlag** [comment]
> Quick update; we were able to build and host KaHyPar v.1.3.0 binaries which should support M1, but there are some issues with the Julia interface failing tests. I'll need to dig a bit deeper (and maybe work with Sebastian) to figure out what's going on.

Let me know if I can be of any help with the failing tests @jalving.

**Comment by jalving** [comment]
Hi @JoeyT1994, can you try updating KaHyPar.jl? (`] update KaHyPar`) The current registered release should be pulling KaHyPar v1.3.0.

I can't find github options to test the CI on M1.  Let us know if you still have this issue.

**Comment by JoeyT1994** [comment]
Sorry for my slow response! 

I just switched back to the aarch64 version of Julia on my M1 to test it and it works great.

Here is the log.

Error from running the previous build:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/51231103/198035211-69274eea-5ca5-4d05-ac39-1d211bd6f0dc.png">


Updating to the new build:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/51231103/198035355-258ea9f6-5767-435b-aa37-bd03948b9533.png">

Running with the new build:

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/51231103/198035996-0bc14fb2-5eae-412e-9c0f-074efa77e0eb.png">


Thank you for updating the package with this. That's very helpful.

**Comment by jalving** [comment]
Great, it works! Thank you for making the bug report and testing this out.
