### ISSUE TITLE
Segmentation fault for certain graphs

### ISSUE THREAD

**Issue by nmoran** [kahypar/KaHyPar.jl#5]
The following matrix causes a segmentation fault when trying to partition

CSV file with matrix elements  `problem_matrix.csv`:
```
cols,rows,values
2,5,1
3,9,1
4,13,1
6,6,1
7,10,1
8,14,1
9,3,1
13,4,1
19,3,1
19,19,1
20,4,1
20,19,1
21,5,1
21,17,1
22,6,1
22,17,1
25,9,1
25,22,1
26,10,1
26,22,1
29,13,1
29,18,1
30,14,1
30,18,1
33,17,1
33,27,1
34,17,1
34,28,1
35,18,1
35,31,1
36,18,1
36,32,1
37,19,1
37,25,1
38,19,1
38,26,1
43,22,1
43,38,1
44,22,1
44,33,1
49,25,1
50,26,1
51,27,1
52,28,1
52,33,1
55,31,1
56,32,1
57,33,1
58,33,1
64,38,1
```

Script to reproduce
```
using KaHyPar
using CSV
using DataFrames
using SparseArrays

df = CSV.read("problem_matrix.csv", DataFrame)
A = sparse(df.rows, df.cols, df.values)

h = KaHyPar.hypergraph(A)
partitions = KaHyPar.partition(h, 2, configuration=:edge_cut)
```

**Comment by SebastianSchlag** [comment]
Hi,
thanks for reaching out. 
@jalving I currently don't have a working Julia installation available and I am not familiar with `SparseArrays`. Do you have any thoughts on would could have gone wrong here?

I first guess would be that this creates a hypergraph that does not adhere to the hMetis format (see http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/manual.pdf Section 3.4).

**Comment by nmoran** [comment]
Hi @SebastianSchlag , thanks for your reply. I looked into the hypergraph structure a little more and found there are many vertices that did not have any edges connected and many edges that do not connect any vertices. After removing these it is working. See example

```
using KaHyPar
using CSV
using DataFrames
using SparseArrays

df = CSV.read("problem_matrix.csv", DataFrame)
A = sparse(df.rows, df.cols, df.values)

non_empty_rows = findall(x -> x != 0, [nnz(A[i,:]) for i in 1:size(A)[1]])
non_empty_cols = findall(x -> x != 0, [nnz(A[:,i]) for i in 1:size(A)[2]])
B = A[non_empty_rows,non_empty_cols]

h = KaHyPar.hypergraph(B)
partitions = KaHyPar.partition(h, 2, configuration=:edge_cut)
```

**Comment by SebastianSchlag** [comment]
Great! Thanks for clarifying. 👍  In genreal, vertices without any edges should not be a problem. However "empty" hyperedges won't work. Would it be okay to close this issue then?

**Comment by jalving** [comment]
@SebastianSchlag Thanks for addressing this so quickly.  If it works for a correct hypergraph I think we can close.  

It might be worth adding some input checks on the hypergraph structure.  I could add this to the Julia interface unless you think input checking should go into the KaHyPar source.

**Comment by nmoran** [comment]
That's good to know this. I'm happy for the issue to be closed. We know what the issue is and can avoid creating problematic hypergraphs. A warning from the Julia interface could be useful to help others diagnose such issues.

**Comment by SebastianSchlag** [comment]
Hi @jalving, if you find the time, I think it would be cool if you could add some general sanity checks to the Julia interface - then users could get native error messages in case the hypergraph is inconsistent.
