### ISSUE TITLE
Clarify macOS instructions

### ISSUE THREAD

**Issue by logankilpatrick** [kahypar/KaHyPar.jl#7]
Hey all, per here: https://github.com/kahypar/KaHyPar.jl#macos-support saying "you must build the package" makes me think I need to enter into the package manager and do "build" which I'm guessing isn't the case. Just wanted to join this out.

**Comment by jalving** [comment]
Thanks for pointing this out.  I think we could make the custom KaHyPar build instructions more clear in general for the julia interface.  The same instructions can also be used to do Linux and Windows installations.  

We can keep this issue open until I write up some better instructions.
